<?php

return [
    'default_tenant_code' => env('ERALMS_DEFAULT_TENANT', 'VABIS'),
    'repository_disk' => env('ERALMS_REPOSITORY_DISK', 'local'),
    'object_storage_disk' => env('ERALMS_OBJECT_STORAGE_DISK', 'object_storage'),
    'cdn' => [
        'url' => env('ERALMS_CDN_URL', ''),
        'asset_url' => env('ASSET_URL', env('ERALMS_CDN_URL', '')),
        'enabled' => (bool) env('ERALMS_CDN_ENABLED', false),
    ],
    'performance' => [
        'api_latency_warn_ms' => (int) env('ERALMS_API_LATENCY_WARN_MS', 500),
        'slow_query_ms' => (int) env('ERALMS_SLOW_QUERY_MS', 200),
        'memory_warn_mb' => (int) env('ERALMS_MEMORY_WARN_MB', 512),
        'queue_wait_warn_seconds' => (int) env('ERALMS_QUEUE_WAIT_WARN_SECONDS', 30),
        'cursor_page_size' => (int) env('ERALMS_CURSOR_PAGE_SIZE', 50),
    ],
    'queues' => [
        'default' => 'default',
        'video_processing' => 'video-processing',
        'quiz_grading' => 'quiz-grading',
        'assignment_processing' => 'assignment-processing',
        'analytics' => 'analytics',
        'notification' => 'notification',
        'certificate' => 'certificate',
        'sync_sis' => 'sync-sis',
        'ai' => 'ai',
    ],
    'cache_prefix' => 'eralms',
    'tenant_header' => 'X-Tenant-Code',
    'audit' => [
        'queue' => env('ERALMS_AUDIT_QUEUE', false),
    ],
    'credentials' => [
        'verify_base_url' => env('ERALMS_CREDENTIAL_VERIFY_URL', 'https://verify.eralms.vn/certificate'),
        'blockchain_ready' => env('ERALMS_CREDENTIAL_BLOCKCHAIN_READY', true),
    ],
    'video' => [
        'storage_disk' => env('VIDEO_STORAGE_DISK', 'public'),
        'cdn_url' => env('VIDEO_CDN_URL', ''),
        'signed_url_ttl' => (int) env('VIDEO_SIGNED_URL_TTL', 1800),
        'default_duration_seconds' => (int) env('VIDEO_DEFAULT_DURATION_SECONDS', 600),
        'default_completion_percent' => (float) env('VIDEO_DEFAULT_COMPLETION_PERCENT', 90),
        'max_suspicious_score_for_completion' => (float) env('VIDEO_MAX_SUSPICIOUS_SCORE_FOR_COMPLETION', 50),
    ],
    'ai' => [
        'provider' => env('ERALMS_AI_PROVIDER', 'local'),
        'embedding_provider' => env('ERALMS_AI_EMBEDDING_PROVIDER', 'local'),
        'embedding_model' => env('ERALMS_AI_EMBEDDING_MODEL', 'hash-embedding-v1'),
        'default_top_k' => (int) env('ERALMS_AI_TOP_K', 4),
        'openrouter' => [
            'api_key' => env('OPENROUTER_API_KEY'),
            'base_url' => env('OPENROUTER_BASE_URL', 'https://openrouter.ai/api/v1'),
            'model' => env('OPENROUTER_MODEL', 'openai/gpt-4o-mini'),
            'referer' => env('OPENROUTER_HTTP_REFERER', env('APP_URL')),
            'title' => env('OPENROUTER_APP_TITLE', env('APP_NAME', 'EraLMS')),
            'temperature' => (float) env('OPENROUTER_TEMPERATURE', 0.2),
            'max_tokens' => (int) env('OPENROUTER_MAX_TOKENS', 700),
            'timeout' => (int) env('OPENROUTER_TIMEOUT', 30),
        ],
    ],
    'menu' => [
        ['key' => 'dashboard', 'title' => 'Tổng quan', 'route_name' => 'dashboard', 'url' => '/', 'icon' => 'layout-dashboard', 'permission_key' => null, 'sort_order' => 10, 'parent_id' => null, 'is_active' => true],
        ['key' => 'system_check', 'title' => 'Kiểm tra hệ thống', 'route_name' => 'admin.lms.system-check', 'url' => '/admin/lms/system-check', 'icon' => 'shield-check', 'permission_key' => 'core.role.manage', 'sort_order' => 20, 'parent_id' => null, 'is_active' => true],
        ['key' => 'analytics', 'title' => 'Learning Analytics', 'route_name' => 'lms.analytics', 'url' => '/analytics', 'icon' => 'chart-column', 'permission_key' => 'analytics.dashboard', 'sort_order' => 30, 'parent_id' => null, 'is_active' => true],
        ['key' => 'reports', 'title' => 'Báo cáo', 'route_name' => 'lms.reports', 'url' => '/reports', 'icon' => 'file-bar-chart', 'permission_key' => 'report.view', 'sort_order' => 40, 'parent_id' => null, 'is_active' => true],
        ['key' => 'ai', 'title' => 'AI trợ giảng', 'route_name' => 'lms.ai', 'url' => '/ai', 'icon' => 'sparkles', 'permission_key' => 'ai.use', 'sort_order' => 50, 'parent_id' => null, 'is_active' => true],
        ['key' => 'mobile', 'title' => 'Mobile learning', 'route_name' => 'lms.mobile', 'url' => '/mobile', 'icon' => 'smartphone', 'permission_key' => 'course.view', 'sort_order' => 60, 'parent_id' => null, 'is_active' => true],
        ['key' => 'courses', 'title' => 'Quản trị khóa học', 'route_name' => 'lms.courses.index', 'url' => '/courses', 'icon' => 'book-open', 'permission_key' => 'course.view', 'sort_order' => 70, 'parent_id' => null, 'is_active' => true],
        ['key' => 'studio', 'title' => 'Studio bài giảng', 'route_name' => 'lms.courses.studio', 'url' => '/courses/studio', 'icon' => 'blocks', 'permission_key' => 'lesson.manage', 'sort_order' => 80, 'parent_id' => null, 'is_active' => true],
        ['key' => 'repository', 'title' => 'Kho học liệu', 'route_name' => 'lms.repository', 'url' => '/repository', 'icon' => 'folder-tree', 'permission_key' => 'repository.view', 'sort_order' => 90, 'parent_id' => null, 'is_active' => true],
        ['key' => 'learning_path', 'title' => 'Lộ trình học tập', 'route_name' => 'lms.learning-path', 'url' => '/learning-path', 'icon' => 'route', 'permission_key' => 'learning_path.view', 'sort_order' => 100, 'parent_id' => null, 'is_active' => true],
        ['key' => 'enrollment', 'title' => 'Quản lý ghi danh', 'route_name' => 'lms.enrollment', 'url' => '/enrollment', 'icon' => 'users', 'permission_key' => 'enrollment.view', 'sort_order' => 110, 'parent_id' => null, 'is_active' => true],
        ['key' => 'video', 'title' => 'Nền tảng video', 'route_name' => 'lms.videos', 'url' => '/videos', 'icon' => 'video', 'permission_key' => 'video.view', 'sort_order' => 120, 'parent_id' => null, 'is_active' => true],
        ['key' => 'question_bank', 'title' => 'Ngân hàng câu hỏi', 'route_name' => 'lms.question-banks', 'url' => '/question-banks', 'icon' => 'circle-help', 'permission_key' => 'question_bank.view', 'sort_order' => 130, 'parent_id' => null, 'is_active' => true],
        ['key' => 'exam', 'title' => 'Kiểm tra online', 'route_name' => 'lms.exams', 'url' => '/exams', 'icon' => 'clipboard-check', 'permission_key' => 'exam.view', 'sort_order' => 140, 'parent_id' => null, 'is_active' => true],
        ['key' => 'assignment', 'title' => 'Bài tập', 'route_name' => 'lms.assignments', 'url' => '/assignments', 'icon' => 'clipboard-list', 'permission_key' => 'assignment.view', 'sort_order' => 150, 'parent_id' => null, 'is_active' => true],
        ['key' => 'assignment_deadlines', 'title' => 'Lịch deadline bài tập', 'route_name' => 'lms.assignments.deadlines', 'url' => '/assignments/deadlines', 'icon' => 'calendar-clock', 'permission_key' => 'assignment.view', 'sort_order' => 155, 'parent_id' => null, 'is_active' => true],
        ['key' => 'gradebook', 'title' => 'Sổ điểm', 'route_name' => 'lms.gradebook', 'url' => '/gradebook', 'icon' => 'table-properties', 'permission_key' => 'gradebook.view', 'sort_order' => 160, 'parent_id' => null, 'is_active' => true],
        ['key' => 'attendance', 'title' => 'Điểm danh online', 'route_name' => 'lms.attendance', 'url' => '/attendance', 'icon' => 'calendar-check', 'permission_key' => 'attendance.view', 'sort_order' => 170, 'parent_id' => null, 'is_active' => true],
        ['key' => 'community', 'title' => 'Cộng đồng học tập', 'route_name' => 'lms.community', 'url' => '/community', 'icon' => 'messages-square', 'permission_key' => 'community.view', 'sort_order' => 180, 'parent_id' => null, 'is_active' => true],
        ['key' => 'surveys', 'title' => 'Khảo sát / Feedback', 'route_name' => 'lms.surveys', 'url' => '/surveys', 'icon' => 'clipboard-pen-line', 'permission_key' => 'survey.view', 'sort_order' => 190, 'parent_id' => null, 'is_active' => true],
        ['key' => 'obe', 'title' => 'OBE / Năng lực', 'route_name' => 'lms.obe', 'url' => '/obe', 'icon' => 'target', 'permission_key' => 'obe.view', 'sort_order' => 200, 'parent_id' => null, 'is_active' => true],
        ['key' => 'standards', 'title' => 'SCORM / LTI / xAPI', 'route_name' => 'lms.standards', 'url' => '/standards/scorm', 'icon' => 'network', 'permission_key' => 'course.view', 'sort_order' => 210, 'parent_id' => null, 'is_active' => true],
        ['key' => 'credentials', 'title' => 'Digital Credential', 'route_name' => 'lms.certificates', 'url' => '/credentials', 'icon' => 'badge-check', 'permission_key' => 'credential.view', 'sort_order' => 220, 'parent_id' => null, 'is_active' => true],
        ['key' => 'career', 'title' => 'Portfolio nghề nghiệp', 'route_name' => 'lms.career', 'url' => '/career', 'icon' => 'briefcase-business', 'permission_key' => 'credential.view', 'sort_order' => 230, 'parent_id' => null, 'is_active' => true],
        ['key' => 'sis', 'title' => 'Đồng bộ SIS', 'route_name' => 'lms.sis', 'url' => '/sis', 'icon' => 'refresh-cw', 'permission_key' => 'integration.view', 'sort_order' => 240, 'parent_id' => null, 'is_active' => true],
        ['key' => 'moodle_parity', 'title' => 'Moodle parity', 'route_name' => 'lms.moodle-parity', 'url' => '/moodle-parity', 'icon' => 'git-compare-arrows', 'permission_key' => 'core.role.manage', 'sort_order' => 250, 'parent_id' => null, 'is_active' => true],
        ['key' => 'security', 'title' => 'Bảo mật', 'route_name' => 'lms.security', 'url' => '/security', 'icon' => 'shield', 'permission_key' => 'security.manage', 'sort_order' => 260, 'parent_id' => null, 'is_active' => true],
        ['key' => 'plugins', 'title' => 'Plugin', 'route_name' => 'lms.plugins', 'url' => '/plugins', 'icon' => 'plug', 'permission_key' => 'plugin.manage', 'sort_order' => 270, 'parent_id' => null, 'is_active' => true],
        ['key' => 'backup', 'title' => 'Sao lưu', 'route_name' => 'lms.backup', 'url' => '/backup', 'icon' => 'database-backup', 'permission_key' => 'backup.manage', 'sort_order' => 280, 'parent_id' => null, 'is_active' => true],
        ['key' => 'uat', 'title' => 'UAT', 'route_name' => 'lms.uat', 'url' => '/uat', 'icon' => 'check-check', 'permission_key' => 'uat.manage', 'sort_order' => 290, 'parent_id' => null, 'is_active' => true],
        ['key' => 'settings', 'title' => 'Cấu hình', 'route_name' => 'lms.settings', 'url' => '/settings', 'icon' => 'settings', 'permission_key' => 'core.tenant.manage', 'sort_order' => 300, 'parent_id' => null, 'is_active' => true],
    ],
];
