<script setup>
import EraLmsLayout from '@/Layouts/EraLmsLayout.vue'

defineProps({
  sessionUser: { type: Object, default: null },
})
defineEmits(['logout'])

const skills=['Kỹ năng nghề 82','Kỹ năng mềm 74','AI Skills 68','Digital Skills 79','Ngoại ngữ 63']
const items=['Đồ án tốt nghiệp','Chứng chỉ an toàn lao động','Dự án nhóm','Cuộc thi tay nghề','Thực tập doanh nghiệp']
</script>
<template><EraLmsLayout :session-user="sessionUser" @logout="$emit('logout')"><template #breadcrumb>Career / Public portfolio</template><main class="min-h-[calc(100vh-6rem)] overflow-hidden rounded-lg border border-slate-200 bg-white text-slate-900"><section class="border-b bg-slate-950 text-white"><div class="mx-auto grid max-w-6xl gap-6 px-6 py-12 md:grid-cols-[1fr_220px]"><div><div class="text-sm text-blue-200">Digital Portfolio Public Portal</div><h1 class="mt-2 text-3xl font-semibold">Học viên EraLMS</h1><p class="mt-3 max-w-2xl text-slate-300">Hồ sơ năng lực học tập, kỹ năng, chứng chỉ và hành trình nghề nghiệp đã được nhà trường xác thực.</p></div><div class="grid aspect-square place-items-center bg-white text-sm font-semibold text-slate-950">QR Profile</div></div></section><section class="mx-auto grid max-w-6xl gap-5 px-6 py-8 lg:grid-cols-[1fr_320px]"><div class="space-y-5"><div class="border p-5"><h2 class="font-semibold">Portfolio Highlights</h2><div class="mt-4 grid gap-3 md:grid-cols-2"><div v-for="item in items" :key="item" class="border bg-slate-50 p-4 text-sm">{{ item }}</div></div></div><div class="border p-5"><h2 class="font-semibold">Career Growth Timeline</h2><div class="mt-4 flex flex-wrap gap-2 text-sm"><span class="rounded bg-slate-100 px-3 py-2">Tuyển sinh</span><span class="rounded bg-slate-100 px-3 py-2">Học tập</span><span class="rounded bg-slate-100 px-3 py-2">Thực tập</span><span class="rounded bg-slate-100 px-3 py-2">Việc làm</span><span class="rounded bg-slate-100 px-3 py-2">Cựu sinh viên</span></div></div></div><aside class="space-y-5"><div class="border p-5"><h2 class="font-semibold">Skill Matrix</h2><div class="mt-3 space-y-2 text-sm"><div v-for="skill in skills" :key="skill" class="flex justify-between border-b py-2"><span>{{ skill.split(' ').slice(0,-1).join(' ') }}</span><strong>{{ skill.split(' ').at(-1) }}</strong></div></div></div><div class="border p-5"><h2 class="font-semibold">Certificate Verification</h2><input class="mt-3 w-full rounded-md border px-3 py-2 text-sm" placeholder="Nhập mã chứng chỉ"/><button class="mt-3 w-full rounded-md bg-slate-950 px-3 py-2 text-sm text-white">Verify</button></div></aside></section></main></EraLmsLayout></template>
